pipeline {
    agent any

    stages {
        stage('Build and Deploy Docker Containers') {
            steps {
                script {
                    sh "cd /home/stas/wordpress-docker-phpmyadmin && /usr/local/bin/docker-compose build"
                    sh "cd /home/stas/wordpress-docker-phpmyadmin && /usr/local/bin/docker-compose up -d"
                }
            }
        }
    }

    post {
        always {
            script {
                sh "cd /home/stas/wordpress-docker-phpmyadmin && /usr/local/bin/docker-compose down"
            }
        }
    }
}
