apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        env:
        - name: WORDPRESS_DB_HOST
          value: "127.0.0.1:3306"
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: username  
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: password 
        - name: WORDPRESS_DB_NAME
          value: "wordpress"  
        ports:
        - containerPort: 80
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.33.1
        command:
        - "/cloud_sql_proxy"
        - "-instances=artful-bonito-436711-i7:europe-west1:your-instance=tcp:3306"
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/secrets/credentials.json"
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloud-sql-instance-credentials
